### ISSUE TITLE
Link from replit audio-libs repo

### ISSUE THREAD

**Issue by wbourne0** [Daniel-Liu-c0deb0t/replit_audio#1]
The library looks pretty solid.  Although we're all for supporting many languages, maintaining libraries for many languages isn't feasible, but we still want to link to libraries that are community contributed.  What do you think about us adding a link to this repo under a "Community contributed libraries" section of our readme at https://github.com/replit/audio-libs?

**Comment by Daniel-Liu-c0deb0t** [comment]
Sure, that would be great!

As a side note, is the audio API [documentation](https://docs.repl.it/repls/audio) up-to-date? It seems to be inconsistent with the Python/JS libraries, which made creating the Rust bindings a bit difficult.

Edit: it seems that the documentation has been updated recently and everything is fine!
